name: EtheriaCore
version: '${project.version}'
main: cykuta.etheriacore.EtheriaCore
api-version: 1.18
authors: [ Cykuta ]
commands:
  tpa:
    description: Send a teleport request to someone user
    aliases: [teleport]
  tpaccept:
    description: Accepts a pending teleport request
    aliases: [aceptar, accept]
  tpdeny:
    description: Deny a pending teleport request
    aliases: [denegar, deny]
  creative:
    description: Change your gamemode
    aliases: [gmc]
  survival:
    description: Change your gamemode
    aliases: [gms]
  adventure:
    description: Change your gamemode
    aliases: [gma]
  spectator:
    description: Change your gamemode
    aliases: [gmsp]
  day:
    description: Change time to day
    aliases: [dia]
  night:
    description: Change time to night
    aliases: [noche]
  sun:
    description: Change weather to sun
    aliases: [soleado]
  rain:
    description: Change weather to rain
    aliases: [lluvia]
  thunder:
    description: Change weather to thunder
    aliases: [tormenta, storm]
  home:
    description: Go to your home here
    aliases: []
  sethome:
    description: Set your home here
    aliases: []
  delhome:
    description: Remove your home
    aliases: []
  register:
    description: Register your account
    aliases: [reg]
  login:
    description: Login to your account
    aliases: [l]
  changepassword:
    description: Change your password
    aliases: [changepass, changepw]